### ISSUE TITLE
document user experience as user stories

### ISSUE THREAD

**Issue by goern** [open-services-group/scrum#15]
As an ODH Admin,
I want to commit a notebook file to a repository, 
and I want to open an issue assigned to a bot,
so that a custom notebook image is delivered to my Open Data Hub deployment,
and so that it is usable via Jupyter Notebook Spawner.

**Comment by goern** [comment]
This will be a `kind/feature` to be refined by a SIG, it shall be a less than 13PT user story tbd in one sprint. quality of the issue is defined by https://github.com/thoth-station/core/blob/master/docs/TermsAndConditionsForTheScrum.md#estimates

**Comment by Gkrumbach07** [comment]
[working doc](https://docs.google.com/document/d/1yY91on5YGuIroJSsKCFi5FebWoba71ermgvmzl9rilk/edit#) -> will be converted into issues with an epic

**Comment by Gkrumbach07** [comment]
Issues have been created @schwesig @goern 

they are referenced to this issue

**Comment by codificat** [comment]
This is outdated by now.
/close
