### ISSUE TITLE
Operate first community cloud topology

### ISSUE THREAD

**Issue by tumido** [open-services-group/scrum#18]
As a service catalog user I want to see the topology of all services and applications available in operate first community cloud including consumed resources like clusters etc.

A service catalog maintainer should know the rules of proper entity mapping used across Operate First community cloud.

- [x] https://github.com/operate-first/service-catalog/issues/60
- [x] https://github.com/operate-first/service-catalog/issues/54
- [x] https://github.com/operate-first/service-catalog/issues/52
- [x] https://github.com/operate-first/service-catalog/issues/55

**Comment by durandom** [comment]
@tumido what does 'cloud survey' mean in this context? The issues listed don't look connected, other than chores and bugs

**Comment by schwesig** [comment]
/close
cleanup after change of organisation
