### ISSUE TITLE
set up CD of BYON feature in os-climate

### ISSUE THREAD

**Issue by goern** [open-services-group/scrum#21]
As a BYON/CNBi developer,
I want to merge a Pull Request against the ODH repo (or fork),
so that the HEAD of main branch is deployed to the OS-Climate environment - or ODH DataScience cluster

## Acceptance Criteria

- [x] #32
- [x] #37

/sig devsecops
/kind feature
/triage needs-information

https://issues.redhat.com/browse/RHODS-2211

**Comment by goern** [comment]
@codificat please update this issue with the latest updates from https://docs.google.com/document/d/1jz4j07Q8gkv9H-23BgOp_4qN3uI29JsuP-_kTKEj-e8/edit#heading=h.ktb4q28asi4v

**Comment by codificat** [comment]
> @codificat please update this issue with the latest updates from https://docs.google.com/document/d/1jz4j07Q8gkv9H-23BgOp_4qN3uI29JsuP-_kTKEj-e8/edit#heading=h.ktb4q28asi4v

The updates from the meeting on 18/Aug around the CD env are part of https://github.com/thoth-station/opendatahub-cnbi/pull/6 (more related to #32 than to this issue though)

/assign
/triage accepted
/lifecycle active

**Comment by codificat** [comment]
This is now superseded by https://github.com/thoth-station/opendatahub-cnbi/issues/20
/close
