### ISSUE TITLE
Onboard ODH DataScience cluster to Operate First

### ISSUE THREAD

**Issue by durandom** [open-services-group/scrum#22]
The cluster will be added to the operate first processes and infrastructure. The DS team will keep cluster-admin privileges. 
The goal is to understand a gap in developing ODH components in a "managed" cluster.

@HumairAK please complete the acceptance criteria list

- [ ] add cluster to RHACM
- [ ] add Operate First SSO to cluster
- [ ] deploy os-c JupyterHub
- [ ] add monitoring

the current cluster is in AWS and contains GPUs, similar to the os-c clusters

**Comment by durandom** [comment]
![Image](https://user-images.githubusercontent.com/161888/180221855-a5d1f07e-e56f-4b1f-b23a-e1c0b0a6f0dc.png)

cc @MichaelClifford @erikerlandson

**Comment by MichaelClifford** [comment]
Thanks @durandom ! 

Do we need to "deploy os-c JupyterHub"? This cluster all ready has an ODH instance running with JupyterHub

**Comment by HumairAK** [comment]
Feedback: 

- Onboard Cluster docs non existed 
- ACM access point should be linked service (Service catalog?) 
- Docs should give alternative suggestion to auth if it cannot be dependent on infra identitatem
-

**Comment by schwesig** [comment]
mentioned to @codificat
