### ISSUE TITLE
spike into GitHub bot usage to create notebook images

### ISSUE THREAD

**Issue by durandom** [open-services-group/scrum#27]
As a GitHub bot,
I want to react on a github issue,
so I want to build and deliver a CNBi to a repo on the ODH internal registry,
so that it could be imported to ODH,
and so that it is usable via Jupyter Notebook Spawner.

# Acceptance Criteria

- [ ] pipelines can be triggered via API or curl call, parameter: git repo url
- [ ] pipelines create container image and publish to registry
- [ ] pipelines add annotations and labels required for ODH
- [ ] meteor is reused
- [ ] pipeline can be trigger via opening a github issue

# References
* meteor pipelines
* aicoe-ci pipelines

**Comment by codificat** [comment]
The approach we currently suggest for CNBi delivery is not via bots or GitHub issues, but through an operator instead (reusing the meteor operator).

See https://github.com/thoth-station/opendatahub-cnbi for more details

**Comment by codificat** [comment]
Superseded by https://github.com/thoth-station/opendatahub-cnbi/issues/22
/close
