### ISSUE TITLE
Scale 19x Workshop Support

### ISSUE THREAD

**Issue by durandom** [open-services-group/scrum#3]
Acceptance criteria: 

- [x] Identify resources, requirements
- [x] Identify environment to use  (with a preference for use of existing services)
- [x] Prepare environment for use by workshop  (with a preference for use of existing services)
- [x] Starting documentation on recreating this workshop

**Comment by HumairAK** [comment]
This can me marked completed ( I don't have permisisons to check the boxes :smile: )

**Comment by schwesig** [comment]
- [x] link to the document

**Comment by HumairAK** [comment]
>  link to the document


https://github.com/operate-first/apps/tree/master/workshops/aiops-tools
workshop docs by the workshop team: https://ocp-ci-analysis.catalog.meteor.zone/docs/workshop/prerequisites.html
