### ISSUE TITLE
documentation of the pipeline, source repos, target clusters, build from branch?

### ISSUE THREAD

**Issue by goern** [open-services-group/scrum#32]
As a BYON/CNBi developer,
I want to read up how and where the components I work on get deployed,
so that I can build and deploy development branches

**Comment by codificat** [comment]
Status update:


The target cluster for CNBi CD is OSC's osc-cl1 cluster.

Deployment of opendatahub is driven by the [odh-manifests](https://github.com/opendatahub-io/odh-manifests/) repo:

-   Operate First maintains a [fork](https://github.com/operate-first/odh-manifests) where manifests are customized in branches. The [osc-cl1-byon branch on that fork](https://github.com/operate-first/odh-manifests/tree/osc-cl1-byon) is used for the OSC cluster1 deployment
-   ODH components to be deployed are specified in <https://github.com/operate-first/apps/tree/master/kfdefs/overlays/osc/osc-cl1>
-   The target namespace for the deployment is `opf-jupyterhub-stage`

ArgoCD [deploys BYON's version of the odh-dashboard](https://github.com/operate-first/odh-manifests/blob/34b43f6b2e2fe1195b37709736a89d64c3bf4411/odh-dashboard/base/deployment.yaml#L30) in the opf-jupyterhub-stage namespace ([as configured](https://github.com/operate-first/apps/blob/92c9d16c1d69e2a87075e2cf45f03dbf55324aa5/kfdefs/overlays/osc/osc-cl1/jupyterhub-stage/kfdef.yaml) in the apps repo). That image is built from <https://github.com/opendatahub-io/odh-dashboard/tree/BYON> and available at `quay.io/repository/operate-first/odh-dashboard:byon`.

Right now, accessing the settings &rarr; notebook images
(<https://odh-dashboard-opf-jupyterhub-stage.apps.odh-cl1.apps.os-climate.org/notebookImages>)
crashes (blank page), with this logged in the browser's js console:

    TypeError: t is undefined
        ae NotebookImagesTable.tsx:130
        ae NotebookImagesTable.tsx:126
        React 6
        unstable_runWithPriority scheduler.production.min.js:19
        React 5
        a useWatchNotebookImages.tsx:38
        promise callback*a useWatchNotebookImages.tsx:35
        o useWatchNotebookImages.tsx:45
        React 2
        unstable_runWithPriority scheduler.production.min.js:19
        React 3
        B scheduler.production.min.js:17
        onmessage scheduler.production.min.js:14
    react-dom.production.min.js:209:194
        React 5
        unstable_runWithPriority scheduler.production.min.js:19
        React 4
        unstable_runWithPriority scheduler.production.min.js:19
        React 5
        a useWatchNotebookImages.tsx:38
        (Async: promise callback)
        a useWatchNotebookImages.tsx:35
        o useWatchNotebookImages.tsx:45
        React 2
        unstable_runWithPriority scheduler.production.min.js:19
        React 3
        B scheduler.production.min.js:17
        onmessage scheduler.production.min.js:14

The stage namespace also has a manifest of the BYON validation/import pipeline:

    $ tkn p ls
    NAME                           AGE            LAST RUN                                 STARTED        DURATION   STATUS
    byon-import-jupyterhub-image   15 weeks ago   byon-import-jupyterhub-image-run-r8jc6   14 weeks ago   1 minute   Succeeded

This seems to have been manually deployed.

Question: @goern where do you think is the best place to persist this type of documentation? ODH? Operate First?

**Comment by codificat** [comment]
> The stage namespace also has a manifest of the BYON validation/import pipeline:
> This seems to have been manually deployed.

It is *not* manually deployed: the pipeline manifest comes from ODH: https://github.com/operate-first/odh-manifests/tree/osc-cl1-byon/jupyterhub/jupyterhub/overlays/byon

**Comment by codificat** [comment]
> Question: @goern where do you think is the best place to persist this type of documentation? ODH? Operate First?

Answering myself: this will be documented in the new https://github.com/thoth-station/opendatahub-cnbi/ repository

**Comment by codificat** [comment]
The initial documentation was added in https://github.com/thoth-station/opendatahub-cnbi/pull/6

Further updates should come as part of the work on https://github.com/thoth-station/opendatahub-cnbi/issues/20
/close
