### ISSUE TITLE
create ADR on git repository usage

### ISSUE THREAD

**Issue by goern** [open-services-group/scrum#33]
As a Developer of the CNBi feature,
I want to take an architectural decision if and how git is used in the feature,
so that I can propose that decision to my stakeholders
and so that I can inform my fellow developers of what we do ;)

# Acceptance Criteria

- [ ] ADR is accepted by ODH community
- [ ] rough cut implementation plan

**Comment by codificat** [comment]
Superseded by https://github.com/thoth-station/opendatahub-cnbi/issues/15
/close
