### ISSUE TITLE
Thoth API Endpoint to provide version of analysed Python packages and versions

### ISSUE THREAD

**Issue by goern** [open-services-group/scrum#36]
# references

* https://docs.google.com/document/d/1kEP4PEuWQAP4S1uqWEGTd1GMWHEr-SwUfKmGBaioMNE/edit?disco=AAAAc85IVjA
* https://docs.google.com/document/d/1kEP4PEuWQAP4S1uqWEGTd1GMWHEr-SwUfKmGBaioMNE/edit?disco=AAAAeH38ox4

**Comment by schwesig** [comment]
/close
cleanup after change of organisation
