### ISSUE TITLE
document CNBi feature design

### ISSUE THREAD

**Issue by codificat** [open-services-group/scrum#38]
As a developer of the CNBi feature for ODH
I want to have a document that describes the functionality that is being implemented and how it is designed,
so that I have an understanding of the components involved and their interactions and dependencies

## Acceptance criteria

- [x] A public document exists that explains the Custom Notebook Image (CNBi) functionality
- [ ] The documentation includes a description of the components involved
- [x] The documentation has diagrams that illustrate the functionality, the components, and their relationships
- [ ] The documentation includes pointers to further details / sources

**Comment by codificat** [comment]
There is a new repository to host the CNBi documentation: https://github.com/thoth-station/opendatahub-cnbi

The entry point to the documentation will be the [README file](https://github.com/thoth-station/opendatahub-cnbi/blob/main/README.md) in that repository. This document is currently being actively worked on in a collaborative way at https://hackmd.io/@thoth-station/ryWW3dsRc

**Comment by goern** [comment]
see https://hackmd.io/6BgU6fdSRvyMLZNPwGykfg

**Comment by codificat** [comment]
Need to also document the pipelines, and add pointers to additional refs (e.g. byon, odh dashboard etc)

**Comment by codificat** [comment]
Superseded by https://github.com/thoth-station/opendatahub-cnbi/issues/22
/close
