### ISSUE TITLE
Create a process for SRE On-Call and support handling for Operate First Cloud

### ISSUE THREAD

**Issue by HumairAK** [open-services-group/scrum#4]
Goal: 

Spread the work of being on-call across the SRE team.

Acceptance Criteria: 

- [ ] Documentation on a set of processes for the Operate First Community Cloud SRE team
- [ ] The person on-call should be responsible for tackling most of the SRE work, and support queries, during their period of on call. 
- [ ] On-Call role also involves resolving existing issues
- [ ] On-Call role also involves updating existing docs, and adding new resolution/support documentation as they perform their on-call duties. Such that future problems are able to be self serviced without involvement of SRE team (if applicable).
- [ ] Process should encourage breaking down silos

**Comment by durandom** [comment]
@tumido @mimotej @SamoKopecky @harshad16 @Gregory-Pereira @schwesig the plan is to expand the team doing on-call SRE, so please work with @HumairAK on this process since it'll affect y'all 😸

**Comment by HumairAK** [comment]
Please have a look at the proposed adr here: https://github.com/operate-first/blueprint/pull/108 
And let me know if I have missed anything. 

fyi @schwesig

**Comment by schwesig** [comment]
it's all checked (permissions are no set yet)
--> done/approved
