### ISSUE TITLE
Install available plugins to backstage

### ISSUE THREAD

**Issue by durandom** [open-services-group/scrum#7]
https://github.com/operate-first/service-catalog/issues?q=is%3Aissue+is%3Aopen+Plugin

- [x] https://github.com/operate-first/service-catalog/issues/20
- [x] https://github.com/operate-first/service-catalog/issues/19
- [x] https://github.com/operate-first/service-catalog/issues/18
- [x] https://github.com/operate-first/service-catalog/issues/17
- [x] https://github.com/operate-first/service-catalog/issues/15
- [x] https://github.com/operate-first/service-catalog/issues/14
- [x] https://github.com/operate-first/service-catalog/issues/13
- [x] https://github.com/operate-first/service-catalog/issues/12

**Comment by tumido** [comment]
Wrap this up by showcasing it via https://github.com/operate-first/service-catalog/issues/25

**Comment by schwesig** [comment]
/close
cleanup after change of organisation
