### ISSUE TITLE
Make Peribolos (really) production ready

### ISSUE THREAD

**Issue by tumido** [open-services-group/scrum#8]
Reslove following:

- [x] https://github.com/operate-first/peribolos-as-a-service/issues/164
- [x] https://github.com/operate-first/peribolos-as-a-service/issues/60
- [x] https://github.com/operate-first/peribolos-as-a-service/issues/165
- [x] https://github.com/operate-first/peribolos-as-a-service/issues/166
- [x] https://github.com/operate-first/peribolos-as-a-service/issues/167
- [x] https://github.com/operate-first/peribolos-as-a-service/issues/174
- [x] https://github.com/operate-first/peribolos-as-a-service/issues/184

**Comment by schwesig** [comment]
/close
cleanup after change of organisation
