### ISSUE TITLE
Bootstrap robozome

### ISSUE THREAD

**Issue by tumido** [open-services-group/scrum#9]
Help out in migration of https://github.com/tssala23/Onboarding-Automation to https://github.com/operate-first/robozome

- [x] Migrate repository
- [ ] Setup CI/CD, integrations and apps
- [ ] Achieve compliance with the [template](https://github.com/operate-first/probot-template)
- [x] https://github.com/operate-first/probot-extensions/issues/35

**Comment by schwesig** [comment]
/close
cleanup after change of organisation
